version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: radious
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --reload
    ports:
      - 80:8000
    volumes:
      - .:/usr/src/app/
      - staticfiles:/usr/src/app/
      - mediafiles:/usr/src/app/

volumes:
  staticfiles:
  mediafiles:
