FROM python:3.10-alpine

WORKDIR /usr/src/app

ADD . /usr/src/app/

RUN pip install -r ./requirements.txt
RUN python manage.py makemigrations
RUN python manage.py migrate
RUN python manage.py fill_radio_stations
RUN python manage.py collectstatic --no-input
