FROM python:3.10-alpine as builder

WORKDIR /usr/src/app

COPY . .

RUN pip install -r ./requirements.txt
RUN python manage.py makemigrations
RUN python manage.py migrate
RUN python manage.py fill_radio_stations
RUN python manage.py collectstatic --no-input
