# Generated by Django 4.2.1 on 2023-05-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Электронная почта')),
                ('rating', models.PositiveIntegerField(db_index=True, verbose_name='Оценка')),
                ('message', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Сообщение')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
        migrations.CreateModel(
            name='Ganre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('stream_url', models.URLField(db_index=True, unique=True, verbose_name='Url потока')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created', models.DateField(auto_now_add=True, verbose_name='Время создания')),
                ('visible', models.BooleanField(default=True, verbose_name='Видимость')),
                ('preview', models.ImageField(upload_to='previews/', verbose_name='Превью')),
                ('ganre', models.ManyToManyField(blank=True, to='radio.ganre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Радио',
                'verbose_name_plural': 'Радио',
            },
        ),
    ]
