# Generated by Django 4.2.1 on 2023-05-27 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='radio',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='radio.radio', verbose_name='Радио'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='radio',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='previews/', verbose_name='Превью'),
        ),
    ]
