# Generated by Django 4.2.1 on 2023-06-01 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_feedback_radio_alter_radio_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='radio',
            name='preview',
            field=models.ImageField(blank=True, default='//media//previews/default.png', null=True, upload_to='previews/', verbose_name='Превью'),
        ),
    ]
